kind: Deployment
apiVersion: apps/v1
metadata:
  name: my-java-springboot
spec:
  replicas: 0
  selector:
    matchLabels:
      app: java-springboot-app
  template:
    metadata:
      labels:
        app: java-springboot-app
    spec:
      serviceAccount: builder
      volumes:
        - name: "my-csi-volume"
          csi:
            driver: "csi.sharedresource.openshift.io"
            readOnly: true
            volumeAttributes:
              sharedSecret: "my-share"
      containers:
        - name: my-java-springboot
          image: java-springboot-image:latest
          volumeMounts:
            - name: "my-csi-volume"
              mountPath: "/app/config"
              readOnly: true
          ports:
            - name: http
              containerPort: 8081
              protocol: TCP
          env:
            - name: "greeting.file.path"
              value: "/app/config/greeting-message"
          resources:
            requests:
              memory: "180Mi"
              cpu: "11m"
---
kind: Service
apiVersion: v1
metadata:
  name: my-java-springboot-svc
spec:
  ports:
    - name: http-8081
      port: 8081
      protocol: TCP
      targetPort: 8081
  selector:
    app: java-springboot-app
